### ISSUE TITLE
As for the label of the spcup_2022_eval_part1/2 dataset

### ISSUE THREAD

**Issue by yveszq** [awsaf49/synatt#2]
Hi, thank you for the code you provided. I would like to obtain the  label of the spcup_2022_eval_part1/2 dataset. Would you please to provide me with it? Thank you in advance.

**Comment by awsaf49** [comment]
Hi, thank you for your interest in our project. Unfortunately, we didn't have access to the Eval 1 & 2 dataset. The results shown in the paper were actually presented by the organizers during the final event at ICASSP'22. Therefore, you might need to contact the organizers to access the labels.
